# Generated by Django 6.0.7 on 2026-08-04 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='staffing.service')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='staffing.position')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='staffing.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='positions',
            field=models.ManyToManyField(related_name='staff_members', through='staffing.StaffPosition', to='staffing.position'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('name', 'service'), name='unique_position_per_service'),
        ),
        migrations.AddConstraint(
            model_name='staffposition',
            constraint=models.UniqueConstraint(fields=('staff', 'position'), name='unique_staff_position'),
        ),
    ]
