# Generated by Django 6.0.7 on 2026-08-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='scheduling.event')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='staffing.staff')),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.UniqueConstraint(fields=('event', 'staff', 'start', 'end'), name='unique_unavailable_slot')],
            },
        ),
    ]
