# Generated by Django 6.0.7 on 2026-08-04 11:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pin_hash', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.event')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staffing.service')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='ShiftPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staffing.position')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='scheduling.shift')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='staffing.staff')),
                ('shift_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.shiftposition')),
            ],
            options={
                'ordering': ['shift_position', 'staff'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('service', 'event', 'start', 'end'), name='unique_shift_for_service_event_time'),
        ),
        migrations.AddConstraint(
            model_name='shiftposition',
            constraint=models.UniqueConstraint(fields=('shift', 'position'), name='unique_scheduling_shift_position'),
        ),
        migrations.AddConstraint(
            model_name='shiftposition',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='scheduling_shift_position_amount_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('shift_position', 'staff'), name='unique_scheduling_shift_assignment'),
        ),
    ]
